# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ryqCH_-h3V8PS8cURXozr4PWniL_R7-k
"""

import pandas as pd
import time

dados = pd.read_csv('Municipios.csv')
#Ordem correta
print(dados)
#Decrescente
ini = time.time()
print(dados.sort_values(by=['IBGE'],ascending=[False]))
des = time.time()

#Crescente
ini = 0
ini = time.time()
print(dados.sort_values(by=['IBGE'],ascending=[True]))
cre = time.time()

#Random
ini = 0
ini = time.time()
dados.sort_values(by=['Municipio'],ascending=[False])
rd = time.time()

print("--Tempos-- ")
print('Ordem crescente ',cre)
print('Ordem decrescente',des)
print('Random ',rd)